---
title: "NGO"
author: "Loïs NGO"
format:
  html: default
  pdf: default
cache: true
editor: 
  markdown: 
    wrap: 72
---

## Setup

```{r, echo=FALSE, warning=FALSE}
#| message: false
here::i_am("grades_test.Rproj")
library(here)
library(vroom)
library(dplyr)
library(tidyr)
library(magrittr)
library(ggplot2)
theme_set(theme_bw())
```

# Introduction

## Question 1

```{r}
#| message: false
grades <- vroom(here("grades.csv"))
grades <- grades %>%
  mutate(id = as.integer(id)) %>%
  mutate(group = as.factor(group)) %>%
  mutate(trimester = as.factor(trimester))
```

# Simple anlyses

## Question 2

```{r}
nrow(grades)
```

The data set contains `{r} nrow(grades)` grades.

## Question 3

```{r}
library(dplyr)
grades %>%
  distinct(id)%>%
  nrow()

# The data set contains `{r} grades %>% distinct(id) %>% nrow()` students.#
```

## Question 4

```{r}
students <- grades %>%
  distinct(id, group) %>%
  arrange(id)
```

```{r}
students %>%
  slice_head(n = 5) %>%
  knitr::kable()
```

## Question 5

```{r}
students %>%
  group_by(group) %>%
  summarise(nb_students = n()) %>%
  mutate(group = as.factor(group)) %>%
  ggplot(aes(x = group, y = nb_students, fill = group)) +
  geom_bar(stat = "identity") +
  labs(x = "Group", y = "Number of Students", title = "Number of Students per Group")
```

## Question 6

```{r}
grades %>%
  filter(course == "Renewable Energy and Sustainable Living") %>%
  mutate(group = as.factor(group)) %>%
  group_by(group) %>%
  summarize(avg_grade = mean(grade)) %>%
  ggplot(aes(x = group, y = avg_grade, fill = group)) +
  geom_col(stat = "identity") +
  labs(x = "Group", y = "Average Grade", title = "Average Grades in Renewable Energy and Sustainable Living")
```

## Question 7

```{r}
ggplot(grades, aes(x = grade, color = trimester)) +
  geom_density() +
  labs(title = "Distribution of Grades by Semester")
```

```{r}
ggplot(grades, aes(x = trimester, y = grade, fill = trimester)) +
  geom_violin() +
  labs(title = "Distribution of Grades by Trimester")
```

# Attendance analysis

## Question 8

```{r, warning=FALSE}
grades_per_student <- grades %>%
  group_by(id, group) %>%
  summarize(nb_grades = n())%>%
  select(id, group, nb_grades)

knitr::kable(head(grades_per_student, 5))
```

| Minimum | Maximum | Average | Median |
|---------|---------|---------|--------|
| `{r} min(grades_per_student$nb_grades)`       | `{r} max(grades_per_student$nb_grades)`      | `{r} mean(grades_per_student$nb_grades)`       | `{r} median(grades_per_student$nb_grades)`      |

: Summary statistics (number of grades)

## Question 9
```{r}
q9 <- grades %>%
  filter(course == "Radiation Ecology and Environmental Science") %>%
  group_by(id, group) %>%
  summarize(nb_grades = n())

knitr::kable(head(q9, 5))
```




